version: "3.8"
services:
  vue-app:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    container_name: carta_front
    ports:
      - 8080:8080
    volumes:
      - ./src/front/carta:/app
    tty: true
    environment:
      - NODE_ENV=development
