FROM node:18.12.0-buster

ENV TZ Asia/Tokyo

WORKDIR /app

# COPY ./docker/vue/*.js /app

RUN apt update
    # npm install && \
    # npm install -g agentkeepalive --save \
    # npm install -g npm@latest && \
    # npm install -g @vue/cli
